name: party_planner
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment: # <-- ADICIONE ESTA SEÇÃO AQUI
  sdk: '^3.8.0-278.1.beta' # <-- E ESTA LINHA COM A VERSÃO SUGERIDA

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5